name: CI Pipeline
 
on:
  workflow_dispatch:
  push:
    branches: [main]  # Запускать только при пуше в ветку main
 
jobs:
  build:
    runs-on: ubuntu-latest  # Используем GitHub-hosted runner с Ubuntu
 
    steps:
      - uses: actions/checkout@v3  # Клонирует код из репозитория
      
      - name: Installing dependencies
        run: npm ci

      - name: Linting
        run:  npm run lint

      - name: Testing
        run: npm run test
